dist: bionic
os: linux
language: php

before_script:
  - phpenv config-rm xdebug.ini || true

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly
  include:
    - php: 7.4
    - php: 7.2
      # if: branch = master AND fork = false
      env: UPDATE_RESOURCES=true

install:
  - composer install

script:
  - ./ci/update.sh
  - ./vendor/bin/phpunit
  - ./vendor/bin/psalm
  - ./vendor/bin/phpstan analyse -l 5 src
  - ./ci/publish.sh
