language: php

before_script:
  - phpenv config-rm xdebug.ini || true

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly
  include:
    - php: 7.4
    - php: 7.4
      if: branch = auto-update-resources
      env: UPDATE_RESOURCES=true

install:
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/psalm
  - ./vendor/bin/phpstan analyse -l 5 src
  - ./update-resources.sh

sudo: false
